#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# 测试凭证与上下文单独存一份，不进 apps/api/.env（.env.* 已 gitignore）
ENV_FILE=.env.workorder-test

PASS=0; FAIL=0
HTTP_CODE=""; BODY=""

ok()  { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; PASS=$((PASS + 1)); }
bad() { printf '  %s✗%s %s\n' "$RED" "$RESET" "$1"; FAIL=$((FAIL + 1)); }

check() {
  local label="$1"; shift
  if "$@" >/dev/null 2>&1; then ok "$label"; else bad "$label"; fi
}

post_json() {
  local url="$1"; shift
  local resp
  resp=$(curl -sS -m 15 -w $'\n%{http_code}' -X POST "$url" \
    -H 'Content-Type: application/json' "$@" 2>&1) || true
  HTTP_CODE=${resp##*$'\n'}
  BODY=${resp%$'\n'*}
}

json_field() { sed -n "s/.*\"$1\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p" | head -n1; }

has_code() { grep -q "\"code\"[[:space:]]*:[[:space:]]*\"$1\"" <<<"$BODY"; }
has_data_true() { grep -q '"data"[[:space:]]*:[[:space:]]*true' <<<"$BODY"; }
starts_wo() { [[ -n "$1" && "$1" == WO* ]]; }

aes_encrypt() {
  local md5 key_hex iv_hex
  md5=$(printf '%s' "$2" | openssl dgst -md5 -r | cut -d' ' -f1)
  key_hex=$(printf '%s' "${md5:0:16}" | od -An -tx1 -v | tr -d ' \n')
  iv_hex=$(printf '%s' '8765432112345678' | od -An -tx1 -v | tr -d ' \n')
  printf '%s' "$1" | openssl enc -aes-128-cbc -K "$key_hex" -iv "$iv_hex" | od -An -tx1 -v | tr -d ' \n'
}

PUSH_PATH="/api/integrations/jb-insurance/work-orders"

banner "退费异常工单 API 联调自测"

stage "环境与凭证"
say "测两条链路：推送（平台→工单，POST ${PUSH_PATH}）与回调（工单→平台，AES 加密报文）。"
say "需要被测 API 在跑：本地 pnpm dev（默认 :3000），或填 dev 环境地址。"
for k in JB_INSURANCE_PUSH_TOKEN JB_INSURANCE_CALLBACK_SECRET JB_INSURANCE_CALLBACK_URL; do
  if [[ -z "$(_existing "$k" || true)" && -f apps/api/.env ]]; then
    v=$(grep -E "^${k}=" apps/api/.env 2>/dev/null | tail -n1 | cut -d= -f2- | tr -d '"' || true)
    [[ -n "${v:-}" ]] && { write_env "$k" "$v" >/dev/null; note "已从 apps/api/.env 预填 ${k}"; }
  fi
done
for c in curl openssl od; do
  command -v "$c" >/dev/null 2>&1 || { warn "缺少依赖：$c"; exit 1; }
done
ask JB_TEST_BASE_URL "API base URL [默认 http://localhost:3000]:"
[[ -z "$JB_TEST_BASE_URL" ]] && JB_TEST_BASE_URL="http://localhost:3000"
JB_TEST_BASE_URL="${JB_TEST_BASE_URL%/}"
ask_secret JB_INSURANCE_PUSH_TOKEN "推送 Bearer token:"
ask_secret JB_INSURANCE_CALLBACK_SECRET "回调 AES secret（只测推送可留空）:"
ask JB_INSURANCE_CALLBACK_URL "平台回调地址（只测推送可留空）:"
write_env JB_TEST_BASE_URL "$JB_TEST_BASE_URL"
[[ -n "$JB_INSURANCE_PUSH_TOKEN" ]]      && write_env JB_INSURANCE_PUSH_TOKEN "$JB_INSURANCE_PUSH_TOKEN"
[[ -n "$JB_INSURANCE_CALLBACK_SECRET" ]] && write_env JB_INSURANCE_CALLBACK_SECRET "$JB_INSURANCE_CALLBACK_SECRET"
[[ -n "$JB_INSURANCE_CALLBACK_URL" ]]    && write_env JB_INSURANCE_CALLBACK_URL "$JB_INSURANCE_CALLBACK_URL"
[[ -n "$JB_INSURANCE_PUSH_TOKEN" ]] || { warn "推送 token 为空，后续推送用例会全失败"; }
post_json "$JB_TEST_BASE_URL$PUSH_PATH" -d '{}'
if [[ "$HTTP_CODE" == "401" ]]; then
  note "服务可达（无 token 返回 401，符合契约）。"
elif [[ "$HTTP_CODE" == "000" ]]; then
  warn "连不上 $JB_TEST_BASE_URL —— 先起服务（pnpm dev）再重跑。"
  confirm "仍然继续？" || exit 1
else
  note "服务可达（HTTP $HTTP_CODE）。"
fi

stage "AES 加解密自测向量"
say "用契约里的固定向量验证本工具的加密实现（secret=dev-test-secret）。"
VEC_PLAIN='{"sysOrderId":"TEST001","endorNo":"TEST001_NO1_001","actualAmount":"100.00","workOrderNumber":"WO100001"}'
VEC_WANT='ad24504c3b0216d2863bcb404c78446e19f9c153e19d8b3156df3eca02fa4b9775c4f4a163907111d6e0d5f505757fb4bce7a0a189c2f85dbc6c9ef9d21dcb5abf3d755d4c0ae1bdcbf896fda39077160e882fed32843e6d8567d40aeb5ac406c819ff646a5edef134e21c46d91874b4'
vec_got=$(aes_encrypt "$VEC_PLAIN" "dev-test-secret")
check "固定向量加密结果与契约一致" test "$vec_got" = "$VEC_WANT"
if [[ "$vec_got" != "$VEC_WANT" ]]; then
  warn "加密实现与契约不符，Stage 7 的回调模拟不可信。"
  note "want: $VEC_WANT"
  note "got:  $vec_got"
fi
pause

stage "推送 · 成功建单"
SYS_ORDER_ID=$(_existing JB_TEST_SYS_ORDER_ID || true)
ENDOR_NO=$(_existing JB_TEST_ENDOR_NO || true)
if [[ -z "$SYS_ORDER_ID" || -z "$ENDOR_NO" ]]; then
  SYS_ORDER_ID="WIZ$(date +%Y%m%d%H%M%S)"
  ENDOR_NO="${SYS_ORDER_ID}_NO1_$(date +%s)"
fi
REFUND_TIME="$(date '+%Y-%m-%d %H:%M:%S')"
PUSH_BODY=$(cat <<EOF
{"sysOrderId":"$SYS_ORDER_ID","endorNo":"$ENDOR_NO","workOrderType":"卡异常-退费失败","expectedAmount":"100.00","refundCreateTime":"$REFUND_TIME","refundTrade":[{"tradeNo":"1","payNo":"PAY$SYS_ORDER_ID","expectedAmount":"100.00"}],"holderName":"张三","holderPhone":"13888888888","companyName":"泰康在线","productId":"P10001","productName":"泰康百万医疗险","policyNo":"P$SYS_ORDER_ID","failureReason":"wizard 联调自测"}
EOF
)
say "POST $PUSH_PATH"
note "endorNo = ${ENDOR_NO}（全链路幂等键，回调阶段会原样用上）"
post_json "$JB_TEST_BASE_URL$PUSH_PATH" -H "Authorization: Bearer $JB_INSURANCE_PUSH_TOKEN" -d "$PUSH_BODY"
note "HTTP $HTTP_CODE ← $BODY"
WORK_ORDER_NUMBER=$(json_field workOrderNumber <<<"$BODY")
check "HTTP 200（业务错误也走 200）" test "$HTTP_CODE" = 200
check "code=0000 建单成功" has_code 0000
check "返回工单号 ${WORK_ORDER_NUMBER:-（空）}" starts_wo "$WORK_ORDER_NUMBER"
if [[ -n "$WORK_ORDER_NUMBER" ]]; then
  write_env JB_TEST_SYS_ORDER_ID "$SYS_ORDER_ID" >/dev/null
  write_env JB_TEST_ENDOR_NO "$ENDOR_NO" >/dev/null
  write_env JB_TEST_WORK_ORDER_NUMBER "$WORK_ORDER_NUMBER" >/dev/null
  note "sysOrderId/endorNo/工单号已存 ${ENV_FILE}，供 Stage 7 回调复用。"
fi
pause

stage "推送 · 幂等重发"
say "原样重发同一 endorNo，契约要求返回 0000 且工单号与首次一致、不重复建单。"
post_json "$JB_TEST_BASE_URL$PUSH_PATH" -H "Authorization: Bearer $JB_INSURANCE_PUSH_TOKEN" -d "$PUSH_BODY"
note "HTTP $HTTP_CODE ← $BODY"
again=$(json_field workOrderNumber <<<"$BODY")
check "HTTP 200" test "$HTTP_CODE" = 200
check "code=0000（幂等重复也算成功）" has_code 0000
check "工单号与首次一致（${again:-空} vs ${WORK_ORDER_NUMBER:-空}）" \
  test -n "$WORK_ORDER_NUMBER" -a "$again" = "$WORK_ORDER_NUMBER"
pause

stage "推送 · 认证失败"
say "故意用错 token，契约要求 HTTP 401（401 仅表示认证失败）。"
post_json "$JB_TEST_BASE_URL$PUSH_PATH" -H "Authorization: Bearer wizard-wrong-token" -d "$PUSH_BODY"
note "HTTP $HTTP_CODE ← $BODY"
check "HTTP 401" test "$HTTP_CODE" = 401
check "报文 code=9998" has_code 9998
pause

stage "推送 · 参数校验失败"
say "缺 endorNo，契约要求 HTTP 200 + code=9998（平台侧不要重试，修报文后再发）。"
post_json "$JB_TEST_BASE_URL$PUSH_PATH" -H "Authorization: Bearer $JB_INSURANCE_PUSH_TOKEN" \
  -d "{\"sysOrderId\":\"$SYS_ORDER_ID\",\"workOrderType\":\"卡异常-退费失败\",\"expectedAmount\":\"100.00\",\"refundCreateTime\":\"$REFUND_TIME\",\"refundTrade\":[{\"tradeNo\":\"1\",\"payNo\":\"PAY$SYS_ORDER_ID\",\"expectedAmount\":\"100.00\"}]}"
note "HTTP $HTTP_CODE ← $BODY"
check "HTTP 200（参数错不走 4xx）" test "$HTTP_CODE" = 200
check "code=9998 参数校验失败" has_code 9998
pause

stage "回调 · 模拟工单完结"
if [[ -z "${JB_INSURANCE_CALLBACK_URL:-}" || -z "${JB_INSURANCE_CALLBACK_SECRET:-}" ]]; then
  note "未配 JB_INSURANCE_CALLBACK_URL / JB_INSURANCE_CALLBACK_SECRET，跳过回调模拟。"
  note "配好后重跑本脚本即可（已存值会带出来）。"
elif [[ -z "${WORK_ORDER_NUMBER:-}" ]]; then
  warn "Stage 3 没拿到工单号，跳过。可先单独跑通推送再重跑。"
else
  say "按契约加密回调明文，POST 到平台回调地址，模拟工单完结回传。"
  CB_PLAIN="{\"sysOrderId\":\"$SYS_ORDER_ID\",\"endorNo\":\"$ENDOR_NO\",\"actualAmount\":\"100.00\",\"workOrderNumber\":\"$WORK_ORDER_NUMBER\",\"remark\":\"wizard 联调自测完结\",\"operator\":\"wizard\"}"
  note "明文: $CB_PLAIN"
  if confirm "将向 ${JB_INSURANCE_CALLBACK_URL} 发送模拟回调，继续？"; then
    cb_body=$(aes_encrypt "$CB_PLAIN" "$JB_INSURANCE_CALLBACK_SECRET")
    post_json "$JB_INSURANCE_CALLBACK_URL" -d "{\"channel\":\"WORK-ORDER\",\"body\":\"$cb_body\"}"
    note "HTTP $HTTP_CODE ← $BODY"
    check "HTTP 200" test "$HTTP_CODE" = 200
    check "code=0000 平台已处理" has_code 0000
    check "data=true（不再重发）" has_data_true
    if has_code 9999; then note "平台返回 9999：工单系统会按 5m→30m→2h 退避重试。"; fi
    if has_code 9998; then note "平台返回 9998：解密/参数失败，不会重试，转人工。"; fi
  else
    note "已跳过。"
  fi
fi

finish

printf '  结果：%s%d 通过%s / %s%d 失败%s\n' "$GREEN" "$PASS" "$RESET" "$RED" "$FAIL" "$RESET"
(( FAIL == 0 ))
